- hosts: all
  become: true
  tasks:

  - name: update repository index
    pacman:
      update_cache: yes

  - name: remove apache2 package
    pacman:
      name: apache
      state: absent

  - name: install htop
    pacman:
      name: htop
      state: latest