- hosts: all
  become: true
  tasks:
  
  - name: create ansible1 user
    tags:  always
    user:
      name:  ansible1
      groups:  root
       

# updates package cache and installs updated packages Arch linux

  - name: install updates Archlinux
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Archlinux"
    
# updates package cache and installs updated packages Debian systems

  - name: install updates for Linux Mint, Debian Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]

# instalation and removal of packages Arch linux

  - name: remove apache2 package Archlinux
    package:
      name: apache
      state: absent
    when: ansible_distribution == "Archlinux"

  - name: install htop Archlinux
    package:
      name: htop
      state: latest
    when: ansible_distribution == "Archlinux"
    
# moves a configurarion file to target machine

  - name: copy .bashrc file "Debian", "Ubuntu", "Linux Mint"
    copy:
     src: files/bashrcdeb
     dest: /home/mark/.bashrc
     owner: mark
     group: mark
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]

  - name: copy .bashrc file Archlinux
    copy:
     src: files/bashrc
     dest: /home/mark/.bashrc
     owner: mark
     group: mark
    when: ansible_distribution == "Archlinux"
