- hosts: all
  become: true
  tasks:

  - name: update repository index for Archlinux
    package:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: remove apache2 package
    package:
      name: apache
      state: absent
    when: ansible_distribution == "Archlinux"

  - name: install htop
    package:
      name: htop
      state: latest
    when: ansible_distribution == "Archlinux"
    
  - name: update repository index for Linux Mint
    package:
      update_cache: yes
    when: ansible_distribution == "Linux Mint"
    
  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /home/mark/.bashrc
     owner: mark
     group: mark
 
    
