- hosts: all
  become: true
  tasks:

  - name: update repository index for Archlinux
    package:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: remove apache2 package Archlinux
    package:
      name: apache
      state: absent
    when: ansible_distribution == "Archlinux"

  - name: install htop Archlinux
    package:
      name: htop
      state: latest
    when: ansible_distribution == "Archlinux"
    
  - name: update repository index for Linux Mint, Debian Ubuntu
    package:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]
      
  - name: copy .bashrc file Archlinux
    copy:
     src: files/bashrc
     dest: /home/mark/.bashrc
     owner: mark
     group: mark
    when: ansible_distribution == "Archlinux"

  - name: upgrade packages Archlinux
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Archlinux"


  - name: upgrade packages debian
    apt: name=* update_cache=yes state=latest
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]

  - name: copy .bashrc file "Debian", "Ubuntu", "Linux Mint"
    copy:
     src: files/bashrcdeb
     dest: /home/mark/.bashrc
     owner: mark
     group: mark
    when: ansible_distribution in ["Debian", "Ubuntu", "Linux Mint"]
