- hosts: all
  become: true
  tasks:

  - name: update repository index for Archlinux
    pacman:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: remove apache2 package
    pacman:
      name: apache
      state: absent
    when: ansible_distribution == "Archlinux"

  - name: install htop
    pacman:
      name: htop
      state: absent
    when: ansible_distribution == "Archlinux"
    
  - name: update repository index for Linux Mint
    apt:
      update_cache: yes
    when: ansible_distribution == "Linux Mint"
